_target_: src.models.lf_module.LFLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.convolution.tcn.TCN
  num_channels: [30]
  kernel_size: 7
  return_sequences: True
  input_size: 1
  output_size: 1
  bias: True

encoder:
  _target_: src.models.encoders.linear.Linear
  in_size: 1
  out_size: ${model.net.input_size}
decoder:
  _target_: src.models.decoders.linear.Linear
  in_size: ${model.net.output_size}
  out_size: 1
